// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OcdServiceMono.API.Infrastructure.DbContexts;

#nullable disable

namespace OcdServiceMono.API.Migrations
{
    [DbContext(typeof(ReadDomainDbContext))]
    [Migration("20240710084615_InitDB")]
    partial class InitDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OcdServiceMono.API.Models.Entities.CMS.CMS_Post", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Avatar")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("avatar")
                        .HasComment("Đường dẫn ảnh đại diện");

                    b.Property<string>("Content")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("content")
                        .HasComment("Nội dung");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(55)
                        .HasColumnType("character varying(55)")
                        .HasColumnName("created_by")
                        .HasComment("Tài khoản khởi tạo");

                    b.Property<DateTimeOffset>("CreatedDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date_time")
                        .HasComment("Ngày khởi tạo");

                    b.Property<string>("Desc")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("desc")
                        .HasComment("Mô tả ngắn");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active")
                        .HasComment("Tình trạng của bài viết (true: Hoạt động, false: Không hoạt động)");

                    b.Property<bool>("IsHot")
                        .HasColumnType("boolean")
                        .HasColumnName("is_hot")
                        .HasComment("Là tin nổi bật");

                    b.Property<int>("Source")
                        .HasColumnType("integer")
                        .HasColumnName("source")
                        .HasComment("Nguồn của bài viết");

                    b.Property<string>("Status")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("status")
                        .HasComment("Trạng thái của tin bài (da_duyet: Đã duyệt, chua_duyet: Chưa duyệt, ...)");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title")
                        .HasComment("Tiêu đề");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(55)
                        .HasColumnType("character varying(55)")
                        .HasColumnName("updated_by")
                        .HasComment("Tài khoản cập nhập lần cuối");

                    b.Property<DateTimeOffset?>("UpdatedDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_date_time")
                        .HasComment("Ngày cập nhập lần cuối");

                    b.Property<int>("View")
                        .HasColumnType("integer")
                        .HasColumnName("view")
                        .HasComment("Lượt xem");

                    b.HasKey("Id")
                        .HasName("pk_cms_posts");

                    b.ToTable("cms_posts", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
